import { execSync } from "node:child_process";
import { CONFIG, ROOT_DIR } from "./config.mjs";

function runCmd(cmd) {
  return execSync(cmd, { cwd: ROOT_DIR, encoding: "utf-8" }).trim();
}

export function getChangedFiles() {
  try {
    const status = runCmd("git status --porcelain");
    return status ? status.split("\n").map(l => l.trim()) : [];
  } catch (err) {
    console.error("Error getting git status:", err);
    return [];
  }
}

export async function commitAndPushLocal(generated) {
  const commitMessage = `seo(agent): add '${generated.topicName}' AEO question & llms knowledge`;
  
  console.log("[Git] Staging modified files...");
  runCmd("git add src/lib/constants.ts public/llms-full.txt scripts/seo-agent/history.json");

  console.log("[Git] Creating commit...");
  runCmd(`git commit -m "${commitMessage}"`);

  console.log("[Git] Pushing to origin main...");
  const remoteUrl = CONFIG.githubToken
    ? `https://${CONFIG.githubToken}@github.com/${CONFIG.repoOwner}/${CONFIG.repoName}.git`
    : "origin";
  runCmd(`git push ${remoteUrl} main`);

  const commitHash = runCmd("git rev-parse HEAD");
  return {
    success: true,
    commitHash,
    statusText: "تغییرات به شاخه main پوش شدند و دیپلوی خودکار Render آغاز شد! 🚀",
  };
}

export async function createGitHubPullRequest(generated) {
  const branchName = `seo-agent/daily-${Date.now()}`;
  const commitMessage = `seo(agent): add '${generated.topicName}' AEO question & llms knowledge`;

  console.log(`[Git] Creating branch ${branchName}...`);
  runCmd(`git checkout -b ${branchName}`);
  runCmd("git add src/lib/constants.ts public/llms-full.txt scripts/seo-agent/history.json");
  runCmd(`git commit -m "${commitMessage}"`);

  // Push branch using token if available
  const remoteUrl = CONFIG.githubToken
    ? `https://x-access-token:${CONFIG.githubToken}@github.com/${CONFIG.repoOwner}/${CONFIG.repoName}.git`
    : "origin";

  console.log(`[Git] Pushing branch ${branchName}...`);
  runCmd(`git push ${remoteUrl} ${branchName}`);

  // Create PR via GitHub REST API
  if (CONFIG.githubToken) {
    const prRes = await fetch(`https://api.github.com/repos/${CONFIG.repoOwner}/${CONFIG.repoName}/pulls`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${CONFIG.githubToken}`,
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: `🤖 SEO/AEO: ${generated.topicName}`,
        head: branchName,
        base: "main",
        body: `### 🤖 Daily AI SEO & AEO Knowledge Expansion\n\n**Topic:** ${generated.topicName}\n**Target Keyword:** \`${generated.targetKeyword}\`\n\n#### ❓ Question:\n> ${generated.qFa}\n\n#### 💡 Direct Answer (AEO):\n> ${generated.aFa}\n\n#### 📈 Strategic SEO Value:\n${generated.strategicValue}\n\n---\n*Auto-generated by arad-portfolio SEO Agent.*`,
      }),
    });

    if (prRes.ok) {
      const prData = await prRes.json();
      return {
        success: true,
        prUrl: prData.html_url,
        statusText: `یک Pull Request جدید در گیت‌هاب ایجاد شد و منتظر تایید شماست: <a href="${prData.html_url}">مشاهده PR</a>`,
      };
    }
  }

  return {
    success: true,
    statusText: `شاخه ${branchName} به گیت‌هاب پوش شد.`,
  };
}
